#!/bin/bash
# export DOCKER_CLI_EXPERIMENTAL=enabled
# curl -fsSL https://get.docker.com -o get-docker.sh
# sh get-docker.sh
# docker --version
# docker buildx create --use
# # env
# docker buildx build --push \
#        --platform linux/arm/v7,linux/arm64/v8,linux/amd64 \
#        -t $IMAGE_NAME .
echo "I do nothing!"
